version: '3.7'

services:
  db:
    image: postgres:15
    container_name: db-store
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: online_store_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d online_store_db -U postgres -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7
    container_name: redis-store
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
    container_name: app-store
    command:
      - sh
      - -c
      - "alembic upgrade head && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always