"""ad user and profile

Revision ID: 0173edfe63f5
Revises: eb2bf01f9b4b
Create Date: 2024-02-25 19:10:56.896897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0173edfe63f5'
down_revision: Union[str, None] = 'eb2bf01f9b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
