"""ad profile

Revision ID: 2bb5fbc9ae6e
Revises: 0173edfe63f5
Create Date: 2024-02-25 19:20:19.016861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb5fbc9ae6e'
down_revision: Union[str, None] = '0173edfe63f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
