"""create order table

Revision ID: 872b5a669506
Revises: 60a71a231e65
Create Date: 2024-02-25 18:07:03.240734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "872b5a669506"
down_revision: Union[str, None] = "60a71a231e65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
