"""ad updates

Revision ID: eb2bf01f9b4b
Revises: 872b5a669506
Create Date: 2024-02-25 18:17:14.621370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb2bf01f9b4b"
down_revision: Union[str, None] = "872b5a669506"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "count")
    # ### end Alembic commands ###
